
version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/spring-demo/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "spring-boot-starter-parent"
    open-pull-requests-limit: 5
